export default [
  {
    name: "Drink 8 glasses of water",
    category: "Health",
    goalType: "daily",
    suggestedTime: "morning",
    streakCount: 0,
    reminderEnabled: true,
  },
  {
    name: "Read for 20 minutes",
    category: "Personal Development",
    goalType: "daily",
    suggestedTime: "evening",
    streakCount: 0,
    reminderEnabled: true,
  },
  {
    name: "Stretch for 10 minutes",
    category: "Fitness",
    goalType: "daily",
    suggestedTime: "morning",
    streakCount: 0,
    reminderEnabled: false,
  },
  {
    name: "Write in journal",
    category: "Mindfulness",
    goalType: "daily",
    suggestedTime: "night",
    streakCount: 0,
    reminderEnabled: true,
  },
  {
    name: "Meditate for 5 minutes",
    category: "Mental Health",
    goalType: "daily",
    suggestedTime: "morning",
    streakCount: 0,
    reminderEnabled: true,
  },
  {
    name: "Plan tomorrow’s tasks",
    category: "Productivity",
    goalType: "daily",
    suggestedTime: "night",
    streakCount: 0,
    reminderEnabled: true,
  },
  {
    name: "Take a 15-minute walk",
    category: "Health",
    goalType: "daily",
    suggestedTime: "afternoon",
    streakCount: 0,
    reminderEnabled: false,
  },
  {
    name: "No social media for 1 hour",
    category: "Digital Wellness",
    goalType: "daily",
    suggestedTime: "evening",
    streakCount: 0,
    reminderEnabled: true,
  },
  {
    name: "Clean one room",
    category: "Home",
    goalType: "weekly",
    suggestedTime: "weekend",
    streakCount: 0,
    reminderEnabled: false,
  },
  {
    name: "Call a friend or family member",
    category: "Social",
    goalType: "weekly",
    suggestedTime: "weekend",
    streakCount: 0,
    reminderEnabled: true,
  },
];
